version:  3

includes:
  cargo: './scripts/TaskFileCargo.yml'

vars:
  RUST_DIR: src_rust
  RUST_API_PATH: "{{.RUST_DIR}}/src/api.rs"
  DART_LIB_PATH: lib/bridge_generated.dart 
  DART_DECL_PATH: lib/bridge_definitions.dart
  BUILD_NAME : step

tasks:
  local_install_crates:
    cmds:
      - task cargo:frb_gen cargo:cargo_xcode cargo:cargo_ndk cargo:cargo_lipo

  build_ios:
    cmds: 
      - flutter_rust_bridge_codegen
       -r {{.RUST_API_PATH}} 
       -d {{.DART_LIB_PATH}}
       --dart-decl-output {{.DART_DECL_PATH}}
       -c ios/Runner/bridge_generated.h;
      - cd {{.RUST_DIR}} && cargo lipo && cp target/universal/debug/lib{{.BUILD_NAME}}.a ../ios/Runner;
  
  build_android:
    cmds:
      - flutter_rust_bridge_codegen
       -r {{.RUST_API_PATH}} 
       -d {{.DART_LIB_PATH}}
       --dart-decl-output {{.DART_DECL_PATH}};
      - cd {{.RUST_DIR}} && cargo ndk 
        -t x86 -t armeabi-v7a -t arm64-v8a -t x86_64 
        -o ../android/app/src/main/jniLibs build;
  build_macos:
    cmds:
      - flutter_rust_bridge_codegen
       -r {{.RUST_API_PATH}} 
       -d {{.DART_LIB_PATH}}
       --dart-decl-output {{.DART_DECL_PATH}}
       -c macos/Runner/bridge_generated.h;
      - cd {{.RUST_DIR}} && cargo xcode;   