version:  3

vars:
  RUST_DIR: src_rust
  RUST_API_PATH: "{{.RUST_DIR}}/src/api.rs"
  DART_LIB_PATH: lib/bridge_generated.dart 
  DART_DECL_PATH: lib/bridge_definitions.dart
  BUILD_NAME : step
  FRB_CODEGEN: 1.56.0
  CARGO_XCODE: 1.5.0
  CARGO_NDK: 2.12.6
  CARGO_LIPO: 3.2.0

tasks:
  local_install_crates:
    cmds:
      - task frb_gen cargo_xcode cargo_ndk cargo_lipo
  frb_gen: 
    cmds: 
     - cargo install flutter_rust_bridge_codegen@{{.FRB_CODEGEN}}; 

  cargo_xcode:
    cmds:
      - cargo install cargo-xcode@{{.CARGO_XCODE}}

  cargo_ndk: 
    cmds:
      - cargo install cargo-ndk@{{.CARGO_NDK}}

  cargo_lipo: 
    cmds:
      - cargo install cargo-lipo@{{.CARGO_LIPO}}

  build_ios:
    cmds: 
      - flutter_rust_bridge_codegen
       -r {{.RUST_API_PATH}} 
       -d {{.DART_LIB_PATH}}
       --dart-decl-output {{.DART_DECL_PATH}}
       -c ios/Runner/bridge_generated.h;
      - cd {{.RUST_DIR}} && cargo lipo && cp target/universal/debug/hellohq.a ../ios/Runner;
  
  build_android:
    cmds:
      - flutter_rust_bridge_codegen
       -r {{.RUST_API_PATH}} 
       -d {{.DART_LIB_PATH}}
       --dart-decl-output {{.DART_DECL_PATH}};
      - cd {{.RUST_DIR}} && cargo ndk 
        -t x86 -t armeabi-v7a -t arm64-v8a -t x86_64 
        -o ../android/app/src/main/jniLibs build;
  build_macos:
    cmds:
      - flutter_rust_bridge_codegen
       -r {{.RUST_API_PATH}} 
       -d {{.DART_LIB_PATH}}
       --dart-decl-output {{.DART_DECL_PATH}}
       -c macos/Runner/bridge_generated.h;
      - cd {{.RUST_DIR}} && cargo xcode;   